version: '3'
services:
  docqa:
    image: tune-tree:1.0.0
    container_name: tune-tree
    restart: always
    ports:
      - "15000:5000"
    volumes:
      #填写自己宿主机的路径，可以提前创建
      - :path/tune-tree:/app/tune-tree
      - :path/music:/app/music
    environment:
      - TZ=Asia/Shanghai
      #后端校验秘钥
      - ACCESS_KEY=tunetree-2026
      #token有效期
      - MUSIC_ROOT=/app/music
